---

- name: Install packages that allow apt to be used over HTTPS
  apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  vars:
      packages:
          - ca-certificates
          - apt-transport-https
          - curl
          - gnupg
          - lsb-release

- name: Add an apt signing key for Docker
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Get lsb_release
  command: lsb_release -cs
  register: lsb_release

- name: Add Docker Repository
  apt_repository:
      repo: "deb [arch={{ arch }}] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
      state: present

- name: Install docker and its dependecies
  apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
  vars:
      packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io

- name: start docker
  service:
      name: docker
      state: started

- name: Verify the installation is successfull
  command: docker run hello-world
  register: docker_run_hello_world
  failed_when: docker_run_hello_world.rc != 0 or docker_run_hello_world.stdout.find( 'This message shows that your installation appears to be working correctly' ) == -1